baseURL = 'https://example.org/'
title = 'Daily Twitter Insights'
theme = 'paper'

# 多语言配置
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = 'English'
    languageCode = 'en-US'
    weight = 1
    title = 'Daily Twitter Insights'
    [languages.en.params]
      description = 'Daily trending topics from Twitter, powered by AI'
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = 'Home'
        url = '/'
        weight = 1
      [[languages.en.menu.main]]
        name = 'Posts'
        url = '/posts/'
        weight = 2
  
  [languages.zh]
    languageName = '简体中文'
    languageCode = 'zh-CN'
    weight = 2
    title = '每日推特热点'
    [languages.zh.params]
      description = '每日推特热门话题，AI智能整理'
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        name = '首页'
        url = '/zh/'
        weight = 1
      [[languages.zh.menu.main]]
        name = '文章'
        url = '/zh/posts/'
        weight = 2

[params]
  dateFormat = 'January 2, 2006'
  monetagId = 'YOUR_MONETAG_ID' # 请替换为您的Monetag ID
  
  # 自定义样式
  customCSS = ['custom.css']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
